### PR TITLE
Heroku-24: Fix customisation of APT sources list

### LINKED ISSUE #286: Heroku-24: Custom sources list causes APT to pull packages lists for multiple architectures
Our image setup scripts currently override the default Ubuntu APT sources list, in order to disable some unwanted repositories.

However, the way they currently do this is via a hardcoded sources list, which starting with Heroku-24 now includes entries for both AMD64 and ARM64:
https://github.com/heroku/base-images/blob/dc82a80d1ae1ac0579432b5a37123175b6c25514/heroku-24/setup.sh#L9-L37

At first glance one might presume that APT would act sensibly here, and only pull the repo index for the current architecture.

However, it seems APT pulls all indexes, and only takes the current arch into account when actually installing packages.

As such, our customisation to the APT sources causes a wasteful double pull of the indexes:

```
$ docker run --rm --user root heroku/heroku:24-build.nightly apt-get update
Get:1 http://security.ubuntu.com/ubuntu noble-security InRelease [90.7 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports noble InRelease [255 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble InRelease [255 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports noble-updates InRelease [89.7 kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports noble-security InRelease [90.7 kB]
Get:6 http://archive.ubuntu.com/ubuntu noble-updates InRelease [89.7 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports noble/universe arm64 Packages [19.0 MB]
Get:8 http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages [19.3 MB]
Get:9 https://apt.postgresql.org/pub/repos/apt noble-pgdg InRelease [123 kB]
Get:10 https://apt.postgresql.org/pub/repos/apt noble-pgdg/main arm64 Packages [413 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports noble/main arm64 Packages [1780 kB]
Get:12 http://archive.ubuntu.com/ubuntu noble/main amd64 Packages [1813 kB]
Fetched 43.3 MB in 19s (2272 kB/s)
``` 

(note both `amd64` and `arm64` indexes being downloaded)

GUS-W-15576471.

### PR DESCRIPTION
**Pull request by edmorley**
Previously the hardcoded custom APT sources list caused APT to pull indexes for both AMD64 and ARM64, even though only one or the other is ever required.

Now, we instead make edits to the existing architecture-specific default Ubuntu APT sources file (which only includes the config for that architecture, not several architectures). This saves having to hardcode multiple variants of the file in `setup.sh`.

The new implementation intentionally doesn't disable the backports suite (and instead only disables the `multiverse` and `restricted` repositories), since Ubuntu no longer considers that suite by default, starting in Ubuntu 11.04:
https://help.ubuntu.com/community/UbuntuBackports?action=recall&rev=90

Fixes #286.
GUS-W-15576471.

### CODE REVIEW

**Comment by edmorley** [comment]
After this change...

On ARM64:

```
$ dr --platform=linux/arm64 heroku/heroku:24 cat /etc/apt/sources.list.d/ubuntu.sources | rg -v '^#'

Types: deb
URIs: http://ports.ubuntu.com/ubuntu-ports/
Suites: noble noble-updates noble-backports
Components: main universe  
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://ports.ubuntu.com/ubuntu-ports/
Suites: noble-security
Components: main universe  
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

And on AMD64:

```
$ dr --platform=linux/amd64 heroku/heroku:24 cat /etc/apt/sources.list.d/ubuntu.sources | rg -v '^#'

Types: deb
URIs: http://archive.ubuntu.com/ubuntu/
Suites: noble noble-updates noble-backports
Components: main universe  
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg

Types: deb
URIs: http://security.ubuntu.com/ubuntu/
Suites: noble-security
Components: main universe  
Signed-By: /usr/share/keyrings/ubuntu-archive-keyring.gpg
```

File: heroku-24/setup.sh [hunk 1]
```diff
@@ -4,37 +4,17 @@ set -euxo pipefail
...
+# Disable APT repositories that contain packages with potentially problematic licenses.
+# We edit the existing file rather than using our own static file contents, since the repository
+# URIs vary across architectures, so we would otherwise have to hardcode multiple file variants.
+# There are multiple repository configuration lines in the file, all of form:
+# `Components: main universe restricted multiverse`
+# See: https://manpages.ubuntu.com/manpages/noble/en/man5/sources.list.5.html
+for repository_to_disable in multiverse restricted; do
+  # sed doesn't support lookbehind so we instead have to match against the line prefix too
+  # and then preserve it using `\1` in the replacement.
+  sed --in-place --regexp-extended "s/(Components:.*) ?${repository_to_disable}/\1/g" /etc/apt/sources.list.d/ubuntu.sources
```
Comment (colincasey) [inline heroku-24/setup.sh:16]: Minor - For a line like `Components: main universe restricted multiverse` this seems to leave an extra space when replacing a value in the middle of the list.  E.g.; replacing `restricted` gives the following:

```
Components: main universe  multiverse
```

It doesn't seem to affect the output in a major way since both components removed are trailing elements but it could leave extra spaces if they weren't. The modification below accounts for this:

```suggestion
  sed --in-place --regexp-extended "s/(Components:.*) ?${repository_to_disable} ?/\1/g" /etc/apt/sources.list.d/ubuntu.sources
```

**Review by colincasey — CHANGES_REQUESTED** [review]

File: heroku-24/setup.sh (hunk 1 above)
Comment (edmorley) [reply heroku-24/setup.sh:16]: The leading ` ?` was intended to avoid that, but it seems like the `.*` being a greedy match can steal the space due to the optionality of the ` ?`. I'll make the leading space none optional instead.

Comment (edmorley) [reply heroku-24/setup.sh:16]: Adding the second ` ?` misses another case:

```shell
$ echo -e 'Components: keep1 remove-me keep2#\nComponents: keep1 keep2 remove-me#\nComponents:remove-me keep1 keep2#' | sed --regexp-extended "s/(Components:.*) ?remove-me ?/\1/g"
Components: keep1 keep2#
Components: keep1 keep2 #
Components:keep1 keep2#
```

I tried making ``.*`` lazy matching by changing it to `.*?`, however, because the ` ?` is optional, the `.*?` still steals the space:

```
$ echo -e 'Components: keep1 remove-me keep2#\nComponents: keep1 keep2 remove-me#\nComponents:remove-me keep1 keep2#' | sed --regexp-extended "s/(Components:.*?) ?remove-me/\1/g"
Components: keep1  keep2#
Components: keep1 keep2 #
Components: keep1 keep2#
```

Given that both the spec and the original APT sources list uses spaces after the `Components:` prefix, I think it would be safe to just use this:

```console
$ echo -e 'Components: keep1 remove-me keep2#\nComponents: keep1 keep2 remove-me#\nComponents:remove-me keep1 keep2#' | sed --regexp-extended "s/(Components:.*) remove-me/\1/g"
Components: keep1 keep2#
Components: keep1 keep2#
Components:remove-me keep1 keep2#
```

Comment (edmorley) [reply heroku-24/setup.sh]: Fixed in https://github.com/heroku/base-images/pull/287/commits/fbddf963e403b167bd01a511f690636212d66f8f

**Review by colincasey — APPROVED** [review]
